name: OSP Web QA Checks

on: [push, pull_request]

jobs:
  run-linters:
    name: Linters and Formatters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm install

      - name: Linters and Formatters Check
        run: |
         npm run lint
         npm run check
